### PR TITLE
Adding in GLSL Syntax highlighting example

### PR DESCRIPTION
**Pull request by JoshuaBatty**
just adding in the GLSL syntax highlighting example and have also modified the ofxEditorSettings so that the + - / * symbols can be used in front of a keyword and syntax highlighting still occurs.

### CODE REVIEW

**Comment by danomatika** [comment]
I have some updates which fix the punctuation issue. Also, can you remove the project files (Xcode etc)? It's more maintainable in the long run if we don't have to update project files since people can use the ProjectGenerator.

**Comment by JoshuaBatty** [comment]
Great news about fixing the punctuation issue, looking forward to having a look. I have updated my fork now so that each example on includes the /src and /data folders. Let me know if i'v done this correct as this is the first time i've ever done a pull request. Cheers.

**Comment by danomatika** [comment]
I added the example as `glslExample`. I didn't merge the PR because there were still a number of issues with it (gitignore & addon_config.mk were deleted, DecimaMonoPro is a licensed font and not distributable, etc).

Also, I did some major updates on how the highlighter works. It simplifies some things.

**Comment by JoshuaBatty** [comment]
Ok no problem. Just glad I got to contribute something to this awesome library. Im at the airport in transit to Berlin so will pull in the latest changes and merge with my fork as soon as I get a chance. Cheers.

**Pull request closed without merging**
